# Generated by Django 3.0.3 on 2020-03-25 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
